name: Docker Image CI

on:
    push:
        branches: [master]
        paths:
            - 'docker-compose.yml'
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: populate .env file
              run: |
                  touch .env
                  echo "${{ secrets.env_file }}" >> .env
                  cat .env
            - name: docker login
              env:
                  DOCKER_USER: ${{secrets.DOCKER_USER}}
                  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
              run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
            - name: Build the Docker image
              run: docker compose build
            - name: Get image name from docker-compose.yml
              id: image-name
              uses: KJ002/read-yaml@main
              with:
                  file: './docker-compose.yml'
                  key-path: '["services", "server", "image"]'
            - name: Docker push
              run: docker push ${{ steps.image-name.outputs.data }}
